/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package jp.sourceforge.soopy.joytoy.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int black=0x7f020002;
        public static final int blue=0x7f020008;
        public static final int cyan=0x7f02000b;
        public static final int darkgray=0x7f020001;
        public static final int gray=0x7f020009;
        public static final int green=0x7f020004;
        public static final int icon=0x7f020000;
        public static final int lightgray=0x7f020005;
        public static final int magenta=0x7f02000a;
        public static final int red=0x7f020003;
        public static final int white=0x7f020006;
        public static final int yellow=0x7f020007;
    }
    public static final class id {
        public static final int AbsoluteLayout01=0x7f060004;
        public static final int LinearLayout00=0x7f060001;
        public static final int LinearLayout01=0x7f060002;
        public static final int LinearLayout05=0x7f060015;
        public static final int backward_button=0x7f060016;
        public static final int body=0x7f06000f;
        public static final int buttons2=0x7f06000b;
        public static final int clear_button=0x7f06000c;
        public static final int confirm=0x7f060010;
        public static final int console_view=0x7f060009;
        public static final int content_view=0x7f060008;
        public static final int edit_view=0x7f060003;
        public static final int eval_button=0x7f060005;
        public static final int forward_button=0x7f060017;
        public static final int load_button=0x7f060006;
        public static final int main_view=0x7f060000;
        public static final int reference_button=0x7f06000d;
        public static final int reference_view=0x7f060012;
        public static final int reference_web_view=0x7f060014;
        public static final int return_button=0x7f060018;
        public static final int save_button=0x7f060007;
        public static final int text1=0x7f060011;
        public static final int text_view=0x7f06000a;
        public static final int title=0x7f06000e;
        public static final int web_frame=0x7f060013;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int note_edit=0x7f030001;
        public static final int notes_list=0x7f030002;
        public static final int notes_row=0x7f030003;
        public static final int reference=0x7f030004;
    }
    public static final class raw {
        public static final int object1=0x7f040000;
        public static final int object2=0x7f040001;
        public static final int object3=0x7f040002;
        public static final int string=0x7f040003;
        public static final int user_function=0x7f040004;
        public static final int while_statement=0x7f040005;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int body=0x7f050005;
        public static final int clear=0x7f050009;
        public static final int close=0x7f05000b;
        public static final int confirm=0x7f050006;
        public static final int edit_note=0x7f050007;
        public static final int eval=0x7f050008;
        public static final int file=0x7f05000a;
        public static final int menu_delete=0x7f050003;
        public static final int menu_insert=0x7f050002;
        public static final int no_notes=0x7f050001;
        public static final int title=0x7f050004;
    }
}
